# With pytest and target version of Python

FROM python:3.8.2-alpine

RUN pip install pytest pytest_mock

WORKDIR /usr/local/src/caw
# create shims for source code
RUN mkdir -v chris caw && touch README.md

COPY requirements.txt .
RUN pip install -r requirements.txt
COPY setup.py .
RUN pip install -e .

CMD ["pytest"]
