name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  full_test:
    name: Full test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install
        run: |
          pip install -r requirements.txt
          pip install -e .
      - name: Setup CUBE
        uses: FNNDSC/miniChRIS@20211031
      - name: Prepare examples
        run: |
          examples/upload_reconstruction_pipeline.sh
          examples/dummy_pipeline.sh
      - name: Run tests
        env:
          CAW_TEST_FULL: y
        run: python -m unittest
