name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Python unittest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install
        run: |
          pip install -r requirements.txt
          pip install -e .
      - name: Setup CUBE
        uses: FNNDSC/miniChRIS@v5
      - name: Prepare examples
        run: testing/upload_reconstruction_pipeline.sh
      - name: Run tests
        run: python -m unittest
